/**
 * Type definitions for regional phenology (flight curve) data
 * Generated by rbms R library with weekly abundance predictions
 */

/**
 * Weekly abundance predictions for a single year
 * Note: abundance values can be numbers or "NA" strings when data is insufficient
 */
export interface YearlyPhenology {
  year: number;
  weeks: number[];
  abundance: (number | string)[];
}

/**
 * Phenology curves organized by year
 */
export interface PhenologyCurves {
  [year: string]: YearlyPhenology;
}

/**
 * Data quality metrics for a region
 */
export interface RegionalDataQuality {
  transectCount: number;
  totalVisits: number;
  totalCounts: number;
}

/**
 * Phenology data for a single region
 */
export interface RegionalPhenology {
  phenologyCurves: PhenologyCurves;
  dataQuality: RegionalDataQuality;
}

/**
 * All regional phenology data for a species
 */
export interface SpeciesPhenology {
  regions: {
    [region: string]: RegionalPhenology;
  };
}

/**
 * Quality criteria used for filtering transects and species
 */
export interface QualityCriteria {
  minYearsActive: number;
  minVisitsPerYear: number;
  minCountsPerSpecies: number;
  minYearsPerSpecies: number;
  minTransectsPerRegion: number;
}

/**
 * Metadata about the phenology data processing
 */
export interface PhenologyMetadata {
  processingDate: string;
  baselineYear: number;
  regions: string[];
  transectsByRegion: {
    [region: string]: number;
  };
  qualityCriteria: QualityCriteria;
  method: string;
}

/**
 * Complete regional phenology dataset
 */
export interface RegionalPhenologyData {
  metadata: PhenologyMetadata;
  species: {
    [speciesName: string]: SpeciesPhenology;
  };
  speciesList: string[];
}
