const list: Record<string | number | symbol, string> = {
  // Diurnas
  "Pyrgus alveus": "CR",
  "Pyrgus serratulae": "EN",
  "Eumedonia eumedon": "EN",
  "Phengaris alcon": "EN",
  "Brenthis hecate": "EN",
  "Euphydryas desfontainii": "EN",
  "Lycaena virgaureae": "VU",
  "Boloria euphrosyne": "VU",
  "Brenthis ino": "VU",
  "Melitaea aetherie": "VU",
  "Euchloe tagis": "VU",
  "Hamearis lucina": "VU",

  // Noturnas
  "Idaea luteolaria": "CR",
  "Apamea scolopacina": "CR",
  "Chersotis oreina": "CR",
  "Euchalcia modestoides": "CR",
  "Hadena luteocincta": "CR",
  "Axia margarita": "EN",
  "Phragmataecia castaneae": "EN",
  "Callimorpha dominula": "EN",
  "Pelosia plumosa": "EN",
  "Setina cantabrica": "EN",
  "Cyclophora pendularia": "EN",
  "Cyclophora serveti": "EN",
  "Ekboarmia miniaria": "EN",
  "Idaea simplicior": "EN",
  "Lomographa bimaculata": "EN",
  "Scopula immorata": "EN",
  "Siona lineata": "EN",
  "Acronicta cuspis": "EN",
  "Agrotis charoae": "EN",
  "Agrotis clavis": "EN",
  "Anorthoa munda": "EN",
  "Archanara dissoluta": "EN",
  "Athetis pallustris": "EN",
  "Cucullia gnaphalii": "EN",
  "Epipsilia latens": "EN",
  "Globia sparganii": "EN",
  "Hada plebeja": "EN",
  "Lacanobia blenna": "EN",
  "Lateroligia ophiogramma": "EN",
  "Leucania comma": "EN",
  "Pachetra sagittigera": "EN",
  "Panemeria tenebrata": "EN",
  "Drymonia dodonaea": "EN",
  "Rhegmatophila alpina": "EN",

  "Catocala fraxini": "VU",
  "Charissa crenulata": "VU",
  "Idaea humiliata": "VU",
  "Zygaena nevadensis": "VU",
  "Zygaena rhadamanthus": "VU",
};

export default list;
